name: STM32 CI

on: [push]

jobs:
  build:
    name: Build STM32 Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc-arm-none-eabi make

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" -S ${{github.workspace}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: stm32-firmware
          path: ${{github.workspace}}/build/*.elf
